server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.178.32:3306/blog2
    username: pippo
    password: ciacione99
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    format-sql: true

jwt:
  token:
    type: Bearer
  header: Authorization
  secret: password01
  expiration: 10000


default:
  page:
    size: 10